# Introduction to Python & Jupyter Notebook

# 1_Intro_to_Python.ipynb

## Defining Variables

In [4]:
"Hello World"

'Hello World'

In [5]:
greeting = "Hello World"  #this is a string variable (<- this is a comment)

In [6]:
greeting

'Hello World'

In [7]:
greeting = "Hello World" 
greeting

'Hello World'

In [8]:
print(greeting)

Hello World


## Basic Math

Define two variables

In [9]:
a = 2
b = 15

Get the sum

In [11]:
a + b

17

In [12]:
my_sum = a + b #get sum of a & b

In [13]:
#print sum
my_sum

17

Get the product

In [14]:
my_product = a*b
my_product

30

# Import libraries

numpy - Numerical Python

In [15]:
import numpy as np

Define a numpy array

In [24]:
ages_list = [25, 30, 35, 40, 45, 50, 55]  #this is a Python list

In [25]:
ages = np.array(ages_list)

In [26]:
ages

array([25, 30, 35, 40, 45, 50, 55])

Get specific elements - note that in Python, the index starts from 0

In [27]:
ages[0]

25

In [28]:
ages[6]

55

In [29]:
ages[-1]

55

Get subset of elements, based on index range

In [30]:
ages[0:4]

array([25, 30, 35, 40])

In [31]:
ages[:4]

array([25, 30, 35, 40])

In [32]:
ages[1:4]

array([30, 35, 40])

In [33]:
ages[1:]

array([30, 35, 40, 45, 50, 55])

In [34]:
ages[:]

array([25, 30, 35, 40, 45, 50, 55])

In [35]:
ages[::2]

array([25, 35, 45, 55])

In [36]:
ages[::-1]

array([55, 50, 45, 40, 35, 30, 25])

Get subset of elements, based on a condition

In [37]:
ages[ages<40]

array([25, 30, 35])

In [38]:
ages[ages<=40]

array([25, 30, 35, 40])

Get no. of elements or length of array

In [39]:
len(ages)

7

Get the mean, minimum and maximum

In [40]:
ages_mean = np.mean(ages)
ages_mean

40.0

In [41]:
np.min(ages)

25

In [42]:
np.max(ages)

55